"""Cria a estrutura inicial completa do banco

Revision ID: bb7c291c469a
Revises: 
Create Date: 2025-09-10 18:56:29.276266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7c291c469a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('produtor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produtor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtor_documento'), ['documento'], unique=True)

    op.create_table('propriedade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_propriedade', sa.String(length=150), nullable=False),
    sa.Column('endereco', sa.String(length=250), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('produtor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['produtor_id'], ['produtor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_colheita', sa.Date(), nullable=False),
    sa.Column('validade', sa.Date(), nullable=False),
    sa.Column('boas_praticas', sa.Text(), nullable=True),
    sa.Column('qr_code_path', sa.String(length=200), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('propriedade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['propriedade_id'], ['propriedade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lote_data_criacao'), ['data_criacao'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lote_data_criacao'))

    op.drop_table('lote')
    op.drop_table('propriedade')
    with op.batch_alter_table('produtor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtor_documento'))

    op.drop_table('produtor')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
